version: '3'

services:
  postgres:
    image: 'postgres:9.5'
    container_name: postgres_onebitexchange
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  app:
    container_name: app_onebitexchange
    depends_on:
      - postgres
    build: .
    command: bash ./start.sh
    ports:
      - 3000:3000
    environment:
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: postgres
      RAILS_ENV: development
    volumes:
      - .:/onebitexchange
      - gems:/gems

volumes:
  postgres:
  gems:
